# Generated by Django 4.1.5 on 2023-01-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0004_remove_myuser_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='contribution',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
