# Generated by Django 4.1.5 on 2023-01-22 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0005_myuser_contribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUserUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('upload_time', models.DateField()),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='update.myuser')),
            ],
        ),
    ]
