# Generated by Django 4.1.5 on 2023-01-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0006_myuseruploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuseruploads',
            name='file',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
    ]
