# Generated by Django 4.1.5 on 2023-01-22 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0007_myuseruploads_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuseruploads',
            old_name='upload_time',
            new_name='uploadTime',
        ),
    ]
